/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AAChamadaMetdAExpr extends PAExpr
{
    private TId _id_;
    private PAChamada _aChamada_;

    public AAChamadaMetdAExpr()
    {
        // Constructor
    }

    public AAChamadaMetdAExpr(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PAChamada _aChamada_)
    {
        // Constructor
        setId(_id_);

        setAChamada(_aChamada_);

    }

    @Override
    public Object clone()
    {
        return new AAChamadaMetdAExpr(
            cloneNode(this._id_),
            cloneNode(this._aChamada_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAChamadaMetdAExpr(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PAChamada getAChamada()
    {
        return this._aChamada_;
    }

    public void setAChamada(PAChamada node)
    {
        if(this._aChamada_ != null)
        {
            this._aChamada_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aChamada_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._aChamada_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._aChamada_ == child)
        {
            this._aChamada_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._aChamada_ == oldChild)
        {
            setAChamada((PAChamada) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
