/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AArAtbrAComando extends PAComando
{
    private TId _id_;
    private PAExprIni _aExprIni_;

    public AArAtbrAComando()
    {
        // Constructor
    }

    public AArAtbrAComando(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PAExprIni _aExprIni_)
    {
        // Constructor
        setId(_id_);

        setAExprIni(_aExprIni_);

    }

    @Override
    public Object clone()
    {
        return new AArAtbrAComando(
            cloneNode(this._id_),
            cloneNode(this._aExprIni_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArAtbrAComando(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PAExprIni getAExprIni()
    {
        return this._aExprIni_;
    }

    public void setAExprIni(PAExprIni node)
    {
        if(this._aExprIni_ != null)
        {
            this._aExprIni_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aExprIni_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._aExprIni_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._aExprIni_ == child)
        {
            this._aExprIni_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._aExprIni_ == oldChild)
        {
            setAExprIni((PAExprIni) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
