/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import java.util.*;
import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AArBlocoABlocoExp extends PABlocoExp
{
    private final LinkedList<PADecConst> _aDecConst_ = new LinkedList<PADecConst>();
    private PAExpr _aExpr_;

    public AArBlocoABlocoExp()
    {
        // Constructor
    }

    public AArBlocoABlocoExp(
        @SuppressWarnings("hiding") List<?> _aDecConst_,
        @SuppressWarnings("hiding") PAExpr _aExpr_)
    {
        // Constructor
        setADecConst(_aDecConst_);

        setAExpr(_aExpr_);

    }

    @Override
    public Object clone()
    {
        return new AArBlocoABlocoExp(
            cloneList(this._aDecConst_),
            cloneNode(this._aExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArBlocoABlocoExp(this);
    }

    public LinkedList<PADecConst> getADecConst()
    {
        return this._aDecConst_;
    }

    public void setADecConst(List<?> list)
    {
        for(PADecConst e : this._aDecConst_)
        {
            e.parent(null);
        }
        this._aDecConst_.clear();

        for(Object obj_e : list)
        {
            PADecConst e = (PADecConst) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._aDecConst_.add(e);
        }
    }

    public PAExpr getAExpr()
    {
        return this._aExpr_;
    }

    public void setAExpr(PAExpr node)
    {
        if(this._aExpr_ != null)
        {
            this._aExpr_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aExpr_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aDecConst_)
            + toString(this._aExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aDecConst_.remove(child))
        {
            return;
        }

        if(this._aExpr_ == child)
        {
            this._aExpr_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PADecConst> i = this._aDecConst_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PADecConst) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._aExpr_ == oldChild)
        {
            setAExpr((PAExpr) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
