/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AArBoolATipoPrimitivo extends PATipoPrimitivo
{
    private TTipoBool _tipoBool_;

    public AArBoolATipoPrimitivo()
    {
        // Constructor
    }

    public AArBoolATipoPrimitivo(
        @SuppressWarnings("hiding") TTipoBool _tipoBool_)
    {
        // Constructor
        setTipoBool(_tipoBool_);

    }

    @Override
    public Object clone()
    {
        return new AArBoolATipoPrimitivo(
            cloneNode(this._tipoBool_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArBoolATipoPrimitivo(this);
    }

    public TTipoBool getTipoBool()
    {
        return this._tipoBool_;
    }

    public void setTipoBool(TTipoBool node)
    {
        if(this._tipoBool_ != null)
        {
            this._tipoBool_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoBool_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._tipoBool_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._tipoBool_ == child)
        {
            this._tipoBool_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._tipoBool_ == oldChild)
        {
            setTipoBool((TTipoBool) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
