/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import java.util.*;
import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AArChamadaMetodoAChamada extends PAChamada
{
    private TId _id_;
    private final LinkedList<PAListaExpr> _aListaExpr_ = new LinkedList<PAListaExpr>();

    public AArChamadaMetodoAChamada()
    {
        // Constructor
    }

    public AArChamadaMetodoAChamada(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") List<?> _aListaExpr_)
    {
        // Constructor
        setId(_id_);

        setAListaExpr(_aListaExpr_);

    }

    @Override
    public Object clone()
    {
        return new AArChamadaMetodoAChamada(
            cloneNode(this._id_),
            cloneList(this._aListaExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArChamadaMetodoAChamada(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public LinkedList<PAListaExpr> getAListaExpr()
    {
        return this._aListaExpr_;
    }

    public void setAListaExpr(List<?> list)
    {
        for(PAListaExpr e : this._aListaExpr_)
        {
            e.parent(null);
        }
        this._aListaExpr_.clear();

        for(Object obj_e : list)
        {
            PAListaExpr e = (PAListaExpr) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._aListaExpr_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._aListaExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._aListaExpr_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator<PAListaExpr> i = this._aListaExpr_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAListaExpr) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
