/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AArFalsoAExpr extends PAExpr
{
    private TFalso _falso_;

    public AArFalsoAExpr()
    {
        // Constructor
    }

    public AArFalsoAExpr(
        @SuppressWarnings("hiding") TFalso _falso_)
    {
        // Constructor
        setFalso(_falso_);

    }

    @Override
    public Object clone()
    {
        return new AArFalsoAExpr(
            cloneNode(this._falso_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArFalsoAExpr(this);
    }

    public TFalso getFalso()
    {
        return this._falso_;
    }

    public void setFalso(TFalso node)
    {
        if(this._falso_ != null)
        {
            this._falso_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._falso_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._falso_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._falso_ == child)
        {
            this._falso_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._falso_ == oldChild)
        {
            setFalso((TFalso) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
