/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AArObjADecObj extends PADecObj
{
    private PATipoClasse _aTipoClasse_;
    private TId _id_;

    public AArObjADecObj()
    {
        // Constructor
    }

    public AArObjADecObj(
        @SuppressWarnings("hiding") PATipoClasse _aTipoClasse_,
        @SuppressWarnings("hiding") TId _id_)
    {
        // Constructor
        setATipoClasse(_aTipoClasse_);

        setId(_id_);

    }

    @Override
    public Object clone()
    {
        return new AArObjADecObj(
            cloneNode(this._aTipoClasse_),
            cloneNode(this._id_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArObjADecObj(this);
    }

    public PATipoClasse getATipoClasse()
    {
        return this._aTipoClasse_;
    }

    public void setATipoClasse(PATipoClasse node)
    {
        if(this._aTipoClasse_ != null)
        {
            this._aTipoClasse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aTipoClasse_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aTipoClasse_)
            + toString(this._id_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aTipoClasse_ == child)
        {
            this._aTipoClasse_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aTipoClasse_ == oldChild)
        {
            setATipoClasse((PATipoClasse) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
