/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import java.util.*;
import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AArReservadoImprimeAChamada extends PAChamada
{
    private final LinkedList<PAListaExpr> _aListaExpr_ = new LinkedList<PAListaExpr>();

    public AArReservadoImprimeAChamada()
    {
        // Constructor
    }

    public AArReservadoImprimeAChamada(
        @SuppressWarnings("hiding") List<?> _aListaExpr_)
    {
        // Constructor
        setAListaExpr(_aListaExpr_);

    }

    @Override
    public Object clone()
    {
        return new AArReservadoImprimeAChamada(
            cloneList(this._aListaExpr_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArReservadoImprimeAChamada(this);
    }

    public LinkedList<PAListaExpr> getAListaExpr()
    {
        return this._aListaExpr_;
    }

    public void setAListaExpr(List<?> list)
    {
        for(PAListaExpr e : this._aListaExpr_)
        {
            e.parent(null);
        }
        this._aListaExpr_.clear();

        for(Object obj_e : list)
        {
            PAListaExpr e = (PAListaExpr) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._aListaExpr_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aListaExpr_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aListaExpr_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PAListaExpr> i = this._aListaExpr_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAListaExpr) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
