/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AArRelacoesAListaRelacoes extends PAListaRelacoes
{
    private PARelacao _aRelacao_;

    public AArRelacoesAListaRelacoes()
    {
        // Constructor
    }

    public AArRelacoesAListaRelacoes(
        @SuppressWarnings("hiding") PARelacao _aRelacao_)
    {
        // Constructor
        setARelacao(_aRelacao_);

    }

    @Override
    public Object clone()
    {
        return new AArRelacoesAListaRelacoes(
            cloneNode(this._aRelacao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArRelacoesAListaRelacoes(this);
    }

    public PARelacao getARelacao()
    {
        return this._aRelacao_;
    }

    public void setARelacao(PARelacao node)
    {
        if(this._aRelacao_ != null)
        {
            this._aRelacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aRelacao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aRelacao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aRelacao_ == child)
        {
            this._aRelacao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aRelacao_ == oldChild)
        {
            setARelacao((PARelacao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
