/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AASeSenaoAComando extends PAComando
{
    private PAExprInversora _aExprInversora_;
    private PAComandoDois _aComandoDois_;
    private PAComando _aComando_;

    public AASeSenaoAComando()
    {
        // Constructor
    }

    public AASeSenaoAComando(
        @SuppressWarnings("hiding") PAExprInversora _aExprInversora_,
        @SuppressWarnings("hiding") PAComandoDois _aComandoDois_,
        @SuppressWarnings("hiding") PAComando _aComando_)
    {
        // Constructor
        setAExprInversora(_aExprInversora_);

        setAComandoDois(_aComandoDois_);

        setAComando(_aComando_);

    }

    @Override
    public Object clone()
    {
        return new AASeSenaoAComando(
            cloneNode(this._aExprInversora_),
            cloneNode(this._aComandoDois_),
            cloneNode(this._aComando_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAASeSenaoAComando(this);
    }

    public PAExprInversora getAExprInversora()
    {
        return this._aExprInversora_;
    }

    public void setAExprInversora(PAExprInversora node)
    {
        if(this._aExprInversora_ != null)
        {
            this._aExprInversora_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aExprInversora_ = node;
    }

    public PAComandoDois getAComandoDois()
    {
        return this._aComandoDois_;
    }

    public void setAComandoDois(PAComandoDois node)
    {
        if(this._aComandoDois_ != null)
        {
            this._aComandoDois_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aComandoDois_ = node;
    }

    public PAComando getAComando()
    {
        return this._aComando_;
    }

    public void setAComando(PAComando node)
    {
        if(this._aComando_ != null)
        {
            this._aComando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aComando_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aExprInversora_)
            + toString(this._aComandoDois_)
            + toString(this._aComando_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aExprInversora_ == child)
        {
            this._aExprInversora_ = null;
            return;
        }

        if(this._aComandoDois_ == child)
        {
            this._aComandoDois_ = null;
            return;
        }

        if(this._aComando_ == child)
        {
            this._aComando_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aExprInversora_ == oldChild)
        {
            setAExprInversora((PAExprInversora) newChild);
            return;
        }

        if(this._aComandoDois_ == oldChild)
        {
            setAComandoDois((PAComandoDois) newChild);
            return;
        }

        if(this._aComando_ == oldChild)
        {
            setAComando((PAComando) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
