/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AExprNivelUmExpr extends PExpr
{
    private PExprNivelUm _exprNivelUm_;

    public AExprNivelUmExpr()
    {
        // Constructor
    }

    public AExprNivelUmExpr(
        @SuppressWarnings("hiding") PExprNivelUm _exprNivelUm_)
    {
        // Constructor
        setExprNivelUm(_exprNivelUm_);

    }

    @Override
    public Object clone()
    {
        return new AExprNivelUmExpr(
            cloneNode(this._exprNivelUm_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprNivelUmExpr(this);
    }

    public PExprNivelUm getExprNivelUm()
    {
        return this._exprNivelUm_;
    }

    public void setExprNivelUm(PExprNivelUm node)
    {
        if(this._exprNivelUm_ != null)
        {
            this._exprNivelUm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprNivelUm_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprNivelUm_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprNivelUm_ == child)
        {
            this._exprNivelUm_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprNivelUm_ == oldChild)
        {
            setExprNivelUm((PExprNivelUm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
