/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AExprNivelDoisExprNivelUm extends PExprNivelUm
{
    private PExprNivelDois _exprNivelDois_;

    public AExprNivelDoisExprNivelUm()
    {
        // Constructor
    }

    public AExprNivelDoisExprNivelUm(
        @SuppressWarnings("hiding") PExprNivelDois _exprNivelDois_)
    {
        // Constructor
        setExprNivelDois(_exprNivelDois_);

    }

    @Override
    public Object clone()
    {
        return new AExprNivelDoisExprNivelUm(
            cloneNode(this._exprNivelDois_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprNivelDoisExprNivelUm(this);
    }

    public PExprNivelDois getExprNivelDois()
    {
        return this._exprNivelDois_;
    }

    public void setExprNivelDois(PExprNivelDois node)
    {
        if(this._exprNivelDois_ != null)
        {
            this._exprNivelDois_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprNivelDois_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprNivelDois_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprNivelDois_ == child)
        {
            this._exprNivelDois_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprNivelDois_ == oldChild)
        {
            setExprNivelDois((PExprNivelDois) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
