/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AExprNivelSeisExprNivelCinco extends PExprNivelCinco
{
    private PExprNivelSeis _exprNivelSeis_;

    public AExprNivelSeisExprNivelCinco()
    {
        // Constructor
    }

    public AExprNivelSeisExprNivelCinco(
        @SuppressWarnings("hiding") PExprNivelSeis _exprNivelSeis_)
    {
        // Constructor
        setExprNivelSeis(_exprNivelSeis_);

    }

    @Override
    public Object clone()
    {
        return new AExprNivelSeisExprNivelCinco(
            cloneNode(this._exprNivelSeis_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprNivelSeisExprNivelCinco(this);
    }

    public PExprNivelSeis getExprNivelSeis()
    {
        return this._exprNivelSeis_;
    }

    public void setExprNivelSeis(PExprNivelSeis node)
    {
        if(this._exprNivelSeis_ != null)
        {
            this._exprNivelSeis_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprNivelSeis_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprNivelSeis_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprNivelSeis_ == child)
        {
            this._exprNivelSeis_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprNivelSeis_ == oldChild)
        {
            setExprNivelSeis((PExprNivelSeis) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
