/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AExprNivelCincoExprNivelQuatro extends PExprNivelQuatro
{
    private PExprNivelCinco _exprNivelCinco_;

    public AExprNivelCincoExprNivelQuatro()
    {
        // Constructor
    }

    public AExprNivelCincoExprNivelQuatro(
        @SuppressWarnings("hiding") PExprNivelCinco _exprNivelCinco_)
    {
        // Constructor
        setExprNivelCinco(_exprNivelCinco_);

    }

    @Override
    public Object clone()
    {
        return new AExprNivelCincoExprNivelQuatro(
            cloneNode(this._exprNivelCinco_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprNivelCincoExprNivelQuatro(this);
    }

    public PExprNivelCinco getExprNivelCinco()
    {
        return this._exprNivelCinco_;
    }

    public void setExprNivelCinco(PExprNivelCinco node)
    {
        if(this._exprNivelCinco_ != null)
        {
            this._exprNivelCinco_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprNivelCinco_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprNivelCinco_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprNivelCinco_ == child)
        {
            this._exprNivelCinco_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprNivelCinco_ == oldChild)
        {
            setExprNivelCinco((PExprNivelCinco) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
