/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AExprNivelSeteExprNivelSeis extends PExprNivelSeis
{
    private PExprNivelSete _exprNivelSete_;

    public AExprNivelSeteExprNivelSeis()
    {
        // Constructor
    }

    public AExprNivelSeteExprNivelSeis(
        @SuppressWarnings("hiding") PExprNivelSete _exprNivelSete_)
    {
        // Constructor
        setExprNivelSete(_exprNivelSete_);

    }

    @Override
    public Object clone()
    {
        return new AExprNivelSeteExprNivelSeis(
            cloneNode(this._exprNivelSete_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprNivelSeteExprNivelSeis(this);
    }

    public PExprNivelSete getExprNivelSete()
    {
        return this._exprNivelSete_;
    }

    public void setExprNivelSete(PExprNivelSete node)
    {
        if(this._exprNivelSete_ != null)
        {
            this._exprNivelSete_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprNivelSete_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprNivelSete_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprNivelSete_ == child)
        {
            this._exprNivelSete_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprNivelSete_ == oldChild)
        {
            setExprNivelSete((PExprNivelSete) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
