/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AExprNivelOitoExprNivelSete extends PExprNivelSete
{
    private PExprNivelOito _exprNivelOito_;

    public AExprNivelOitoExprNivelSete()
    {
        // Constructor
    }

    public AExprNivelOitoExprNivelSete(
        @SuppressWarnings("hiding") PExprNivelOito _exprNivelOito_)
    {
        // Constructor
        setExprNivelOito(_exprNivelOito_);

    }

    @Override
    public Object clone()
    {
        return new AExprNivelOitoExprNivelSete(
            cloneNode(this._exprNivelOito_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprNivelOitoExprNivelSete(this);
    }

    public PExprNivelOito getExprNivelOito()
    {
        return this._exprNivelOito_;
    }

    public void setExprNivelOito(PExprNivelOito node)
    {
        if(this._exprNivelOito_ != null)
        {
            this._exprNivelOito_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprNivelOito_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprNivelOito_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprNivelOito_ == child)
        {
            this._exprNivelOito_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprNivelOito_ == oldChild)
        {
            setExprNivelOito((PExprNivelOito) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
