/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AExprNivelTresExprNivelDois extends PExprNivelDois
{
    private PExprNivelTres _exprNivelTres_;

    public AExprNivelTresExprNivelDois()
    {
        // Constructor
    }

    public AExprNivelTresExprNivelDois(
        @SuppressWarnings("hiding") PExprNivelTres _exprNivelTres_)
    {
        // Constructor
        setExprNivelTres(_exprNivelTres_);

    }

    @Override
    public Object clone()
    {
        return new AExprNivelTresExprNivelDois(
            cloneNode(this._exprNivelTres_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprNivelTresExprNivelDois(this);
    }

    public PExprNivelTres getExprNivelTres()
    {
        return this._exprNivelTres_;
    }

    public void setExprNivelTres(PExprNivelTres node)
    {
        if(this._exprNivelTres_ != null)
        {
            this._exprNivelTres_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprNivelTres_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprNivelTres_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprNivelTres_ == child)
        {
            this._exprNivelTres_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprNivelTres_ == oldChild)
        {
            setExprNivelTres((PExprNivelTres) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
