/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AExprAritmExprRelacional extends PExprRelacional
{
    private PExprAritm _exprAritm_;

    public AExprAritmExprRelacional()
    {
        // Constructor
    }

    public AExprAritmExprRelacional(
        @SuppressWarnings("hiding") PExprAritm _exprAritm_)
    {
        // Constructor
        setExprAritm(_exprAritm_);

    }

    @Override
    public Object clone()
    {
        return new AExprAritmExprRelacional(
            cloneNode(this._exprAritm_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExprAritmExprRelacional(this);
    }

    public PExprAritm getExprAritm()
    {
        return this._exprAritm_;
    }

    public void setExprAritm(PExprAritm node)
    {
        if(this._exprAritm_ != null)
        {
            this._exprAritm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprAritm_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprAritm_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprAritm_ == child)
        {
            this._exprAritm_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprAritm_ == oldChild)
        {
            setExprAritm((PExprAritm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
