/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AMenorIgualExprRelacional extends PExprRelacional
{
    private PExprRelacional _exprRelacional_;
    private TMenorIgual _menorIgual_;
    private PExprAritm _exprAritm_;

    public AMenorIgualExprRelacional()
    {
        // Constructor
    }

    public AMenorIgualExprRelacional(
        @SuppressWarnings("hiding") PExprRelacional _exprRelacional_,
        @SuppressWarnings("hiding") TMenorIgual _menorIgual_,
        @SuppressWarnings("hiding") PExprAritm _exprAritm_)
    {
        // Constructor
        setExprRelacional(_exprRelacional_);

        setMenorIgual(_menorIgual_);

        setExprAritm(_exprAritm_);

    }

    @Override
    public Object clone()
    {
        return new AMenorIgualExprRelacional(
            cloneNode(this._exprRelacional_),
            cloneNode(this._menorIgual_),
            cloneNode(this._exprAritm_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMenorIgualExprRelacional(this);
    }

    public PExprRelacional getExprRelacional()
    {
        return this._exprRelacional_;
    }

    public void setExprRelacional(PExprRelacional node)
    {
        if(this._exprRelacional_ != null)
        {
            this._exprRelacional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprRelacional_ = node;
    }

    public TMenorIgual getMenorIgual()
    {
        return this._menorIgual_;
    }

    public void setMenorIgual(TMenorIgual node)
    {
        if(this._menorIgual_ != null)
        {
            this._menorIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menorIgual_ = node;
    }

    public PExprAritm getExprAritm()
    {
        return this._exprAritm_;
    }

    public void setExprAritm(PExprAritm node)
    {
        if(this._exprAritm_ != null)
        {
            this._exprAritm_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprAritm_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprRelacional_)
            + toString(this._menorIgual_)
            + toString(this._exprAritm_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprRelacional_ == child)
        {
            this._exprRelacional_ = null;
            return;
        }

        if(this._menorIgual_ == child)
        {
            this._menorIgual_ = null;
            return;
        }

        if(this._exprAritm_ == child)
        {
            this._exprAritm_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprRelacional_ == oldChild)
        {
            setExprRelacional((PExprRelacional) newChild);
            return;
        }

        if(this._menorIgual_ == oldChild)
        {
            setMenorIgual((TMenorIgual) newChild);
            return;
        }

        if(this._exprAritm_ == oldChild)
        {
            setExprAritm((PExprAritm) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
