/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AMenosExprNivelQuatro extends PExprNivelQuatro
{
    private PExprNivelCinco _a_;
    private TMenos _menos_;
    private PExprNivelCinco _b_;

    public AMenosExprNivelQuatro()
    {
        // Constructor
    }

    public AMenosExprNivelQuatro(
        @SuppressWarnings("hiding") PExprNivelCinco _a_,
        @SuppressWarnings("hiding") TMenos _menos_,
        @SuppressWarnings("hiding") PExprNivelCinco _b_)
    {
        // Constructor
        setA(_a_);

        setMenos(_menos_);

        setB(_b_);

    }

    @Override
    public Object clone()
    {
        return new AMenosExprNivelQuatro(
            cloneNode(this._a_),
            cloneNode(this._menos_),
            cloneNode(this._b_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMenosExprNivelQuatro(this);
    }

    public PExprNivelCinco getA()
    {
        return this._a_;
    }

    public void setA(PExprNivelCinco node)
    {
        if(this._a_ != null)
        {
            this._a_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._a_ = node;
    }

    public TMenos getMenos()
    {
        return this._menos_;
    }

    public void setMenos(TMenos node)
    {
        if(this._menos_ != null)
        {
            this._menos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._menos_ = node;
    }

    public PExprNivelCinco getB()
    {
        return this._b_;
    }

    public void setB(PExprNivelCinco node)
    {
        if(this._b_ != null)
        {
            this._b_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._b_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._a_)
            + toString(this._menos_)
            + toString(this._b_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._a_ == child)
        {
            this._a_ = null;
            return;
        }

        if(this._menos_ == child)
        {
            this._menos_ = null;
            return;
        }

        if(this._b_ == child)
        {
            this._b_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._a_ == oldChild)
        {
            setA((PExprNivelCinco) newChild);
            return;
        }

        if(this._menos_ == oldChild)
        {
            setMenos((TMenos) newChild);
            return;
        }

        if(this._b_ == oldChild)
        {
            setB((PExprNivelCinco) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
