/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AMultExprNivelSete extends PExprNivelSete
{
    private PExprNivelSete _exprNivelSete_;
    private TMult _mult_;
    private PExprNivelOito _exprNivelOito_;

    public AMultExprNivelSete()
    {
        // Constructor
    }

    public AMultExprNivelSete(
        @SuppressWarnings("hiding") PExprNivelSete _exprNivelSete_,
        @SuppressWarnings("hiding") TMult _mult_,
        @SuppressWarnings("hiding") PExprNivelOito _exprNivelOito_)
    {
        // Constructor
        setExprNivelSete(_exprNivelSete_);

        setMult(_mult_);

        setExprNivelOito(_exprNivelOito_);

    }

    @Override
    public Object clone()
    {
        return new AMultExprNivelSete(
            cloneNode(this._exprNivelSete_),
            cloneNode(this._mult_),
            cloneNode(this._exprNivelOito_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultExprNivelSete(this);
    }

    public PExprNivelSete getExprNivelSete()
    {
        return this._exprNivelSete_;
    }

    public void setExprNivelSete(PExprNivelSete node)
    {
        if(this._exprNivelSete_ != null)
        {
            this._exprNivelSete_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprNivelSete_ = node;
    }

    public TMult getMult()
    {
        return this._mult_;
    }

    public void setMult(TMult node)
    {
        if(this._mult_ != null)
        {
            this._mult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mult_ = node;
    }

    public PExprNivelOito getExprNivelOito()
    {
        return this._exprNivelOito_;
    }

    public void setExprNivelOito(PExprNivelOito node)
    {
        if(this._exprNivelOito_ != null)
        {
            this._exprNivelOito_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprNivelOito_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exprNivelSete_)
            + toString(this._mult_)
            + toString(this._exprNivelOito_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exprNivelSete_ == child)
        {
            this._exprNivelSete_ = null;
            return;
        }

        if(this._mult_ == child)
        {
            this._mult_ = null;
            return;
        }

        if(this._exprNivelOito_ == child)
        {
            this._exprNivelOito_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exprNivelSete_ == oldChild)
        {
            setExprNivelSete((PExprNivelSete) newChild);
            return;
        }

        if(this._mult_ == oldChild)
        {
            setMult((TMult) newChild);
            return;
        }

        if(this._exprNivelOito_ == oldChild)
        {
            setExprNivelOito((PExprNivelOito) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
