/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class ANegacaoExprNivelCinco extends PExprNivelCinco
{
    private TNegacao _negacao_;
    private PExprNivelSeis _exprNivelSeis_;

    public ANegacaoExprNivelCinco()
    {
        // Constructor
    }

    public ANegacaoExprNivelCinco(
        @SuppressWarnings("hiding") TNegacao _negacao_,
        @SuppressWarnings("hiding") PExprNivelSeis _exprNivelSeis_)
    {
        // Constructor
        setNegacao(_negacao_);

        setExprNivelSeis(_exprNivelSeis_);

    }

    @Override
    public Object clone()
    {
        return new ANegacaoExprNivelCinco(
            cloneNode(this._negacao_),
            cloneNode(this._exprNivelSeis_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANegacaoExprNivelCinco(this);
    }

    public TNegacao getNegacao()
    {
        return this._negacao_;
    }

    public void setNegacao(TNegacao node)
    {
        if(this._negacao_ != null)
        {
            this._negacao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._negacao_ = node;
    }

    public PExprNivelSeis getExprNivelSeis()
    {
        return this._exprNivelSeis_;
    }

    public void setExprNivelSeis(PExprNivelSeis node)
    {
        if(this._exprNivelSeis_ != null)
        {
            this._exprNivelSeis_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exprNivelSeis_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._negacao_)
            + toString(this._exprNivelSeis_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._negacao_ == child)
        {
            this._negacao_ = null;
            return;
        }

        if(this._exprNivelSeis_ == child)
        {
            this._exprNivelSeis_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._negacao_ == oldChild)
        {
            setNegacao((TNegacao) newChild);
            return;
        }

        if(this._exprNivelSeis_ == oldChild)
        {
            setExprNivelSeis((PExprNivelSeis) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
