/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AObjDecObj extends PDecObj
{
    private TObjeto _objeto_;
    private PTipoClasse _tipoClasse_;
    private TId _id_;
    private TPontoVirgula _pontoVirgula_;

    public AObjDecObj()
    {
        // Constructor
    }

    public AObjDecObj(
        @SuppressWarnings("hiding") TObjeto _objeto_,
        @SuppressWarnings("hiding") PTipoClasse _tipoClasse_,
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") TPontoVirgula _pontoVirgula_)
    {
        // Constructor
        setObjeto(_objeto_);

        setTipoClasse(_tipoClasse_);

        setId(_id_);

        setPontoVirgula(_pontoVirgula_);

    }

    @Override
    public Object clone()
    {
        return new AObjDecObj(
            cloneNode(this._objeto_),
            cloneNode(this._tipoClasse_),
            cloneNode(this._id_),
            cloneNode(this._pontoVirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAObjDecObj(this);
    }

    public TObjeto getObjeto()
    {
        return this._objeto_;
    }

    public void setObjeto(TObjeto node)
    {
        if(this._objeto_ != null)
        {
            this._objeto_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._objeto_ = node;
    }

    public PTipoClasse getTipoClasse()
    {
        return this._tipoClasse_;
    }

    public void setTipoClasse(PTipoClasse node)
    {
        if(this._tipoClasse_ != null)
        {
            this._tipoClasse_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._tipoClasse_ = node;
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public TPontoVirgula getPontoVirgula()
    {
        return this._pontoVirgula_;
    }

    public void setPontoVirgula(TPontoVirgula node)
    {
        if(this._pontoVirgula_ != null)
        {
            this._pontoVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoVirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._objeto_)
            + toString(this._tipoClasse_)
            + toString(this._id_)
            + toString(this._pontoVirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._objeto_ == child)
        {
            this._objeto_ = null;
            return;
        }

        if(this._tipoClasse_ == child)
        {
            this._tipoClasse_ = null;
            return;
        }

        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._pontoVirgula_ == child)
        {
            this._pontoVirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._objeto_ == oldChild)
        {
            setObjeto((TObjeto) newChild);
            return;
        }

        if(this._tipoClasse_ == oldChild)
        {
            setTipoClasse((PTipoClasse) newChild);
            return;
        }

        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._pontoVirgula_ == oldChild)
        {
            setPontoVirgula((TPontoVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
