/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import java.util.*;
import jaca.analysis.*;

@SuppressWarnings("nls")
public final class AReservadoImprimeChamada extends PChamada
{
    private TMetodoImprime _metodoImprime_;
    private TParEsq _parEsq_;
    private final LinkedList<PListaExpr> _listaExpr_ = new LinkedList<PListaExpr>();
    private TParDir _parDir_;

    public AReservadoImprimeChamada()
    {
        // Constructor
    }

    public AReservadoImprimeChamada(
        @SuppressWarnings("hiding") TMetodoImprime _metodoImprime_,
        @SuppressWarnings("hiding") TParEsq _parEsq_,
        @SuppressWarnings("hiding") List<?> _listaExpr_,
        @SuppressWarnings("hiding") TParDir _parDir_)
    {
        // Constructor
        setMetodoImprime(_metodoImprime_);

        setParEsq(_parEsq_);

        setListaExpr(_listaExpr_);

        setParDir(_parDir_);

    }

    @Override
    public Object clone()
    {
        return new AReservadoImprimeChamada(
            cloneNode(this._metodoImprime_),
            cloneNode(this._parEsq_),
            cloneList(this._listaExpr_),
            cloneNode(this._parDir_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAReservadoImprimeChamada(this);
    }

    public TMetodoImprime getMetodoImprime()
    {
        return this._metodoImprime_;
    }

    public void setMetodoImprime(TMetodoImprime node)
    {
        if(this._metodoImprime_ != null)
        {
            this._metodoImprime_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._metodoImprime_ = node;
    }

    public TParEsq getParEsq()
    {
        return this._parEsq_;
    }

    public void setParEsq(TParEsq node)
    {
        if(this._parEsq_ != null)
        {
            this._parEsq_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parEsq_ = node;
    }

    public LinkedList<PListaExpr> getListaExpr()
    {
        return this._listaExpr_;
    }

    public void setListaExpr(List<?> list)
    {
        for(PListaExpr e : this._listaExpr_)
        {
            e.parent(null);
        }
        this._listaExpr_.clear();

        for(Object obj_e : list)
        {
            PListaExpr e = (PListaExpr) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._listaExpr_.add(e);
        }
    }

    public TParDir getParDir()
    {
        return this._parDir_;
    }

    public void setParDir(TParDir node)
    {
        if(this._parDir_ != null)
        {
            this._parDir_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parDir_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._metodoImprime_)
            + toString(this._parEsq_)
            + toString(this._listaExpr_)
            + toString(this._parDir_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._metodoImprime_ == child)
        {
            this._metodoImprime_ = null;
            return;
        }

        if(this._parEsq_ == child)
        {
            this._parEsq_ = null;
            return;
        }

        if(this._listaExpr_.remove(child))
        {
            return;
        }

        if(this._parDir_ == child)
        {
            this._parDir_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._metodoImprime_ == oldChild)
        {
            setMetodoImprime((TMetodoImprime) newChild);
            return;
        }

        if(this._parEsq_ == oldChild)
        {
            setParEsq((TParEsq) newChild);
            return;
        }

        for(ListIterator<PListaExpr> i = this._listaExpr_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PListaExpr) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._parDir_ == oldChild)
        {
            setParDir((TParDir) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
