/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.node;

import jaca.analysis.*;

@SuppressWarnings("nls")
public final class TMetodoLe extends Token
{
    public TMetodoLe()
    {
        super.setText(".lê");
    }

    public TMetodoLe(int line, int pos)
    {
        super.setText(".lê");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TMetodoLe(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTMetodoLe(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TMetodoLe text.");
    }
}
