/* This file was generated by SableCC (http://www.sablecc.org/). */

package jaca.lexer;

import java.io.*;
import jaca.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 11:
                        {
                            @SuppressWarnings("hiding") Token token = new11(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 12:
                        {
                            @SuppressWarnings("hiding") Token token = new12(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 13:
                        {
                            @SuppressWarnings("hiding") Token token = new13(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 14:
                        {
                            @SuppressWarnings("hiding") Token token = new14(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 15:
                        {
                            @SuppressWarnings("hiding") Token token = new15(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 16:
                        {
                            @SuppressWarnings("hiding") Token token = new16(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 17:
                        {
                            @SuppressWarnings("hiding") Token token = new17(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 18:
                        {
                            @SuppressWarnings("hiding") Token token = new18(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 19:
                        {
                            @SuppressWarnings("hiding") Token token = new19(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 20:
                        {
                            @SuppressWarnings("hiding") Token token = new20(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 21:
                        {
                            @SuppressWarnings("hiding") Token token = new21(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 22:
                        {
                            @SuppressWarnings("hiding") Token token = new22(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 23:
                        {
                            @SuppressWarnings("hiding") Token token = new23(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 24:
                        {
                            @SuppressWarnings("hiding") Token token = new24(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 25:
                        {
                            @SuppressWarnings("hiding") Token token = new25(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 26:
                        {
                            @SuppressWarnings("hiding") Token token = new26(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 27:
                        {
                            @SuppressWarnings("hiding") Token token = new27(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 28:
                        {
                            @SuppressWarnings("hiding") Token token = new28(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 29:
                        {
                            @SuppressWarnings("hiding") Token token = new29(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 30:
                        {
                            @SuppressWarnings("hiding") Token token = new30(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 31:
                        {
                            @SuppressWarnings("hiding") Token token = new31(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 32:
                        {
                            @SuppressWarnings("hiding") Token token = new32(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 33:
                        {
                            @SuppressWarnings("hiding") Token token = new33(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 34:
                        {
                            @SuppressWarnings("hiding") Token token = new34(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 35:
                        {
                            @SuppressWarnings("hiding") Token token = new35(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 36:
                        {
                            @SuppressWarnings("hiding") Token token = new36(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 37:
                        {
                            @SuppressWarnings("hiding") Token token = new37(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 38:
                        {
                            @SuppressWarnings("hiding") Token token = new38(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 39:
                        {
                            @SuppressWarnings("hiding") Token token = new39(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 40:
                        {
                            @SuppressWarnings("hiding") Token token = new40(
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 41:
                        {
                            @SuppressWarnings("hiding") Token token = new41(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 42:
                        {
                            @SuppressWarnings("hiding") Token token = new42(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 43:
                        {
                            @SuppressWarnings("hiding") Token token = new43(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 44:
                        {
                            @SuppressWarnings("hiding") Token token = new44(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInicio(line, pos); }
    Token new1(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFim(line, pos); }
    Token new2(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TClasse(line, pos); }
    Token new3(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVerdade(line, pos); }
    Token new4(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFalso(line, pos); }
    Token new5(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSe(line, pos); }
    Token new6(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSenao(line, pos); }
    Token new7(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEnquanto(line, pos); }
    Token new8(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TProcedimento(line, pos); }
    Token new9(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFuncao(line, pos); }
    Token new10(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTipoBool(line, pos); }
    Token new11(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TTipoReal(line, pos); }
    Token new12(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new THeranca(line, pos); }
    Token new13(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TObjeto(line, pos); }
    Token new14(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVariavel(line, pos); }
    Token new15(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TConstante(line, pos); }
    Token new16(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TELogico(line, pos); }
    Token new17(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TOuLogico(line, pos); }
    Token new18(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TClasseReservada(line, pos); }
    Token new19(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMetodoImprime(line, pos); }
    Token new20(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMetodoLe(line, pos); }
    Token new21(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentario(text, line, pos); }
    Token new22(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioBloco(text, line, pos); }
    Token new23(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TRelacaoSymbol(line, pos); }
    Token new24(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPontoVirgula(line, pos); }
    Token new25(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TAtribuicao(line, pos); }
    Token new26(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInicioProced(line, pos); }
    Token new27(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParEsq(line, pos); }
    Token new28(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TParDir(line, pos); }
    Token new29(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVirgula(line, pos); }
    Token new30(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPonto(line, pos); }
    Token new31(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TSoma(line, pos); }
    Token new32(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenos(line, pos); }
    Token new33(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMult(line, pos); }
    Token new34(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDiv(line, pos); }
    Token new35(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMod(line, pos); }
    Token new36(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIgual(line, pos); }
    Token new37(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenor(line, pos); }
    Token new38(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TMenorIgual(line, pos); }
    Token new39(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNegacao(line, pos); }
    Token new40(@SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TBarra(line, pos); }
    Token new41(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVazio(text, line, pos); }
    Token new42(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TId(text, line, pos); }
    Token new43(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TIdClass(text, line, pos); }
    Token new44(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNumeroReal(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{9, 9, 1}, {10, 10, 2}, {13, 13, 3}, {32, 32, 4}, {33, 33, 5}, {35, 35, 6}, {37, 37, 7}, {38, 38, 8}, {40, 40, 9}, {41, 41, 10}, {42, 42, 11}, {43, 43, 12}, {44, 44, 13}, {45, 45, 14}, {46, 46, 15}, {47, 47, 16}, {48, 57, 17}, {58, 58, 18}, {59, 59, 19}, {60, 60, 20}, {61, 61, 21}, {62, 62, 22}, {65, 90, 23}, {95, 95, 24}, {97, 97, 25}, {98, 98, 26}, {99, 99, 27}, {100, 100, 25}, {101, 101, 28}, {102, 102, 29}, {103, 104, 25}, {105, 105, 30}, {106, 107, 25}, {108, 108, 31}, {109, 110, 25}, {111, 111, 32}, {112, 112, 33}, {113, 113, 25}, {114, 114, 34}, {115, 115, 35}, {116, 117, 25}, {118, 118, 36}, {119, 122, 25}, {123, 123, 37}, {124, 124, 38}, {192, 192, 39}, {193, 193, 40}, {194, 194, 41}, {195, 195, 42}, {199, 199, 43}, {200, 200, 44}, {201, 201, 45}, {202, 202, 46}, {204, 204, 47}, {205, 205, 48}, {206, 206, 49}, {210, 210, 50}, {211, 211, 51}, {212, 212, 52}, {213, 213, 53}, {217, 217, 54}, {218, 218, 55}, {219, 219, 56}, {224, 224, 57}, {225, 225, 58}, {226, 226, 59}, {227, 227, 60}, {231, 231, 61}, {232, 232, 62}, {233, 233, 63}, {234, 234, 64}, {236, 236, 65}, {237, 237, 66}, {238, 238, 67}, {242, 242, 68}, {243, 243, 69}, {244, 244, 70}, {245, 245, 71}, {249, 249, 72}, {250, 250, 73}, {251, 251, 74}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {{9, 32, -2}, },
            {},
            {{0, 9, 75}, {11, 65535, 75}, },
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {{44, 44, 76}, {48, 57, 17}, {69, 69, 77}, {101, 101, 78}, },
            {{61, 61, 79}, },
            {},
            {{61, 61, 80}, },
            {{61, 61, 81}, },
            {{62, 62, 82}, },
            {{65, 90, 83}, {95, 95, 84}, {97, 122, 85}, {192, 192, 86}, {193, 193, 87}, {194, 194, 88}, {195, 195, 89}, {199, 199, 90}, {200, 200, 91}, {201, 201, 92}, {202, 202, 93}, {204, 204, 94}, {205, 205, 95}, {206, 206, 96}, {210, 210, 97}, {211, 211, 98}, {212, 212, 99}, {213, 213, 100}, {217, 217, 101}, {218, 218, 102}, {219, 219, 103}, {224, 224, 104}, {225, 225, 105}, {226, 226, 106}, {227, 227, 107}, {231, 231, 108}, {232, 232, 109}, {233, 233, 110}, {234, 234, 111}, {236, 236, 112}, {237, 237, 113}, {238, 238, 114}, {242, 242, 115}, {243, 243, 116}, {244, 244, 117}, {245, 245, 118}, {249, 249, 119}, {250, 250, 120}, {251, 251, 121}, },
            {{65, 68, 122}, {69, 69, 123}, {70, 90, 122}, {95, 95, 124}, {97, 122, 125}, {192, 192, 126}, {193, 193, 127}, {194, 194, 128}, {195, 195, 129}, {199, 199, 130}, {200, 200, 131}, {201, 201, 132}, {202, 202, 133}, {204, 204, 134}, {205, 205, 135}, {206, 206, 136}, {210, 210, 137}, {211, 211, 138}, {212, 212, 139}, {213, 213, 140}, {217, 217, 141}, {218, 218, 142}, {219, 219, 143}, {224, 224, 144}, {225, 225, 145}, {226, 226, 146}, {227, 227, 147}, {231, 231, 148}, {232, 232, 149}, {233, 233, 150}, {234, 234, 151}, {236, 236, 152}, {237, 237, 153}, {238, 238, 154}, {242, 242, 155}, {243, 243, 156}, {244, 244, 157}, {245, 245, 158}, {249, 249, 159}, {250, 250, 160}, {251, 251, 161}, },
            {{65, 251, -25}, },
            {{65, 95, -25}, {97, 110, 85}, {111, 111, 162}, {112, 122, 85}, {192, 251, -25}, },
            {{65, 95, -25}, {97, 107, 85}, {108, 108, 163}, {109, 110, 85}, {111, 111, 164}, {112, 251, -28}, },
            {{65, 95, -25}, {97, 109, 85}, {110, 110, 165}, {111, 122, 85}, {192, 251, -25}, },
            {{65, 95, -25}, {97, 97, 166}, {98, 104, 85}, {105, 105, 167}, {106, 116, 85}, {117, 117, 168}, {118, 122, 85}, {192, 251, -25}, },
            {{65, 95, -25}, {97, 108, 85}, {109, 109, 169}, {110, 110, 170}, {111, 251, -30}, },
            {{65, 233, -25}, {234, 234, 171}, {236, 251, -25}, },
            {{65, 95, -25}, {97, 97, 85}, {98, 98, 172}, {99, 116, 85}, {117, 117, 173}, {118, 251, -31}, },
            {{65, 95, -25}, {97, 113, 85}, {114, 114, 174}, {115, 122, 85}, {192, 251, -25}, },
            {{65, 95, -25}, {97, 100, 85}, {101, 101, 175}, {102, 122, 85}, {192, 251, -25}, },
            {{65, 100, -36}, {101, 101, 176}, {102, 251, -36}, },
            {{65, 95, -25}, {97, 97, 177}, {98, 100, 85}, {101, 101, 178}, {102, 251, -36}, },
            {{0, 124, 179}, {125, 125, 180}, {126, 65535, 179}, },
            {},
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{0, 65535, -8}, },
            {{48, 57, 181}, },
            {{45, 45, 182}, },
            {{45, 45, 182}, },
            {},
            {},
            {},
            {{62, 62, 183}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 90, 122}, {95, 251, -26}, },
            {{65, 82, 122}, {83, 83, 184}, {84, 90, 122}, {95, 251, -26}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 251, -124}, },
            {{65, 110, -28}, {111, 111, 185}, {112, 251, -28}, },
            {{65, 95, -25}, {97, 97, 186}, {98, 122, 85}, {192, 251, -25}, },
            {{65, 109, -30}, {110, 110, 187}, {111, 251, -30}, },
            {{65, 95, -25}, {97, 112, 85}, {113, 113, 188}, {114, 122, 85}, {192, 251, -25}, },
            {{65, 107, -29}, {108, 108, 189}, {109, 122, 85}, {192, 251, -25}, },
            {{65, 107, -29}, {108, 108, 190}, {109, 109, 191}, {110, 122, 85}, {192, 251, -25}, },
            {{65, 109, -30}, {110, 110, 192}, {111, 251, -30}, },
            {{65, 95, -25}, {97, 111, 85}, {112, 112, 193}, {113, 122, 85}, {192, 251, -25}, },
            {{65, 236, -25}, {237, 237, 194}, {238, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 95, -25}, {97, 105, 85}, {106, 106, 195}, {107, 122, 85}, {192, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 110, -28}, {111, 111, 196}, {112, 251, -28}, },
            {{65, 95, -25}, {97, 97, 197}, {98, 251, -165}, },
            {{65, 109, -30}, {110, 110, 198}, {111, 251, -30}, },
            {{65, 113, -35}, {114, 114, 199}, {115, 251, -35}, },
            {{65, 113, -35}, {114, 114, 200}, {115, 251, -35}, },
            {{0, 65535, -39}, },
            {},
            {{48, 57, 181}, },
            {{48, 57, 201}, },
            {},
            {{65, 251, -124}, },
            {{65, 107, -29}, {108, 108, 202}, {109, 251, -168}, },
            {{65, 95, -25}, {97, 114, 85}, {115, 115, 203}, {116, 122, 85}, {192, 251, -25}, },
            {{65, 114, -188}, {115, 115, 204}, {116, 251, -188}, },
            {{65, 95, -25}, {97, 116, 85}, {117, 117, 205}, {118, 251, -31}, },
            {{65, 114, -188}, {115, 115, 206}, {116, 251, -188}, },
            {{65, 95, -25}, {97, 103, 85}, {104, 104, 207}, {105, 122, 85}, {192, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 227, -25}, {231, 231, 208}, {232, 251, -25}, },
            {{65, 113, -35}, {114, 114, 209}, {115, 251, -35}, },
            {{65, 95, -25}, {97, 98, 85}, {99, 99, 210}, {100, 122, 85}, {192, 251, -25}, },
            {{65, 100, -36}, {101, 101, 211}, {102, 251, -36}, },
            {{65, 98, -196}, {99, 99, 212}, {100, 251, -196}, },
            {{65, 107, -29}, {108, 108, 213}, {109, 251, -168}, },
            {{65, 226, -25}, {227, 227, 214}, {231, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 95, -25}, {97, 99, 85}, {100, 100, 215}, {101, 122, 85}, {192, 251, -25}, },
            {{48, 57, 201}, },
            {{65, 251, -25}, },
            {{65, 114, -188}, {115, 115, 216}, {116, 251, -188}, },
            {{65, 95, -25}, {97, 115, 85}, {116, 116, 217}, {117, 122, 85}, {192, 251, -25}, },
            {{65, 95, -25}, {97, 97, 218}, {98, 251, -165}, },
            {{65, 110, -28}, {111, 111, 219}, {112, 251, -28}, },
            {{65, 95, -25}, {97, 97, 220}, {98, 251, -165}, },
            {{65, 226, -25}, {227, 227, 221}, {231, 251, -25}, },
            {{65, 95, -25}, {97, 104, 85}, {105, 105, 222}, {106, 122, 85}, {192, 251, -25}, },
            {{65, 104, -211}, {105, 105, 223}, {106, 251, -211}, },
            {{65, 115, -206}, {116, 116, 224}, {117, 251, -206}, },
            {{65, 100, -36}, {101, 101, 225}, {102, 251, -36}, },
            {{65, 251, -25}, },
            {{65, 110, -28}, {111, 111, 226}, {112, 251, -28}, },
            {{65, 95, -25}, {97, 97, 227}, {98, 251, -165}, },
            {{65, 100, -36}, {101, 101, 228}, {102, 251, -36}, },
            {{65, 251, -25}, },
            {{65, 109, -30}, {110, 110, 229}, {111, 251, -30}, },
            {{65, 251, -25}, },
            {{32, 32, 230}, {65, 251, -25}, },
            {{65, 110, -28}, {111, 111, 231}, {112, 251, -28}, },
            {{65, 108, -32}, {109, 109, 232}, {110, 251, -169}, },
            {{65, 110, -28}, {111, 111, 233}, {112, 251, -28}, },
            {{65, 110, -28}, {111, 111, 234}, {112, 251, -28}, },
            {{65, 99, -202}, {100, 100, 235}, {101, 251, -202}, },
            {{65, 251, -25}, },
            {{65, 99, -202}, {100, 100, 236}, {101, 251, -202}, },
            {{65, 251, -25}, },
            {{65, 115, -206}, {116, 116, 237}, {117, 251, -206}, },
            {{100, 100, 238}, },
            {{65, 251, -25}, },
            {{65, 100, -36}, {101, 101, 239}, {102, 251, -36}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{65, 104, -211}, {105, 105, 240}, {106, 251, -211}, },
            {{65, 100, -36}, {101, 101, 241}, {102, 251, -36}, },
            {{65, 110, -28}, {111, 111, 242}, {112, 251, -28}, },
            {{97, 97, 243}, },
            {{65, 251, -25}, },
            {{65, 108, -32}, {109, 109, 244}, {110, 251, -169}, },
            {{65, 251, -25}, },
            {{65, 251, -25}, },
            {{32, 32, 245}, },
            {{65, 100, -36}, {101, 101, 246}, {102, 251, -36}, },
            {{99, 99, 247}, },
            {{65, 109, -30}, {110, 110, 248}, {111, 251, -30}, },
            {{108, 108, 249}, },
            {{65, 115, -206}, {116, 116, 250}, {117, 251, -206}, },
            {{97, 97, 251}, },
            {{65, 110, -28}, {111, 111, 252}, {112, 251, -28}, },
            {{115, 115, 253}, },
            {{65, 251, -25}, },
            {{115, 115, 254}, },
            {{101, 101, 255}, },
            {},
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, 41, 41, 41, 41, 39, 21, 35, 23, 27, 28, 33, 31, 29, 32, 30, 34, 44, -1, 24, 37, -1, -1, 42, 43, 42, 42, 42, 16, 42, 42, 42, 42, 42, 42, 42, 42, -1, 40, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 21, -1, -1, -1, 25, 38, 36, -1, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 43, 42, 42, 42, 42, 42, 42, 42, 42, 42, 20, 42, 17, 42, 42, 5, 42, 42, -1, 22, 44, -1, 26, 18, 42, 42, 42, 42, 42, 42, 1, 42, 42, 42, 42, 42, 42, 42, 14, 42, 44, 10, 42, 42, 42, 42, 42, 42, 42, 42, 42, 42, 11, 42, 42, 42, 15, 42, 4, 42, 42, 42, 42, 42, 42, 6, 42, 2, 42, -1, 9, 42, 0, 13, 42, 42, 42, -1, 19, 42, 3, 7, -1, 42, -1, 42, -1, 42, -1, 42, -1, 8, -1, -1, 12, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
